name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        go build -v .
        go test ./... -v
        
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        extended: true
        
    - name: Hugo Build
      working-directory: docs
      run: hugo --minify
    
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v2.5.1
      with:
        emptyCommits: true
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/public
      
